In [1]:
print("Hello Muhame")

Hello Muhame


In [2]:
import libraries


ModuleNotFoundError: No module named 'libraries'

In [ ]:
import numpy as np
pip install numpy


In [ ]:
pip install numpy

In [ ]:
import libraries

In [ ]:
import numpy as np

In [ ]:
import libraries

In [3]:
import numpy as np

In [5]:
x = 3
print(type(x))

<class 'int'>


In [6]:
x+1

4

In [7]:
x*3

9

In [8]:
x-1

2

In [9]:
x**3

27

In [10]:
x/3

1.0

In [11]:
x//3

1

In [12]:
x<2

False

In [13]:
x>2

True

## Create a rank 1 array

In [14]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [32]:
a
print(type(a))
print(a.shape)
print(a[0],a[1],a[2])
a([0] == 5)
a

<class 'numpy.ndarray'>
(3,)
1 2 3


TypeError: 'numpy.ndarray' object is not callable

# numpy array
 A numpy array is a grid of values, all of the same type, and is indexed by a tuple of non-negative integers.
 
 The number of dimensions in the rank of the array;
 The shape of the array is the tuple of integers giving the size of the array along each dimension
 
 We can initialise numpy arrays from nested python lists and access elements using square brackets ie;
 

In [31]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
b.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

# Numpy con't
Numpy also provides many functions to create arrays
ie if i want to create an raray of an indentity matrix;
np.zeros(2,3) and this is showing that we need a 2,3 matrix in form of zeros
np.ones(2,3) and this will bring in form of 1s
ie;
np.eye refers to an indetity matrix
np.full([2,3],7)creates one of 7s
# NB
We dont use square brackets in functions


In [41]:
#this puts an array of zeros
d = np.zeros((2,3))
print(d)

[[0. 0. 0.]
 [0. 0. 0.]]


In [43]:
#array of ones
h = np.ones((2,3))
print(h)
#array of sevens
full = np.full((2,3),7)
print(full)
#created an indetity matrix
eye = np.eye(2)
print(eye)
# creates a random variables and use .random.random
q = np.random.random((2,2))
print(q)
# This might look like this;
[[0.17153986 0.64038178]
 [0.79910171 0.1329355 ]]



[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7]
 [7 7 7]]
[[1. 0.]
 [0. 1.]]
[[0.17153986 0.64038178]
 [0.79910171 0.1329355 ]]


# Array Math
Basic mtc funcdtions operate elementwise as overlogs and functions in numpy 

In [50]:
z = np.array([[1,2],[3,4]])
r = np.array([[5,6],[7,8]])
# This adds the two matrices
z+r


array([[ 6,  8],
       [10, 12]])

In [51]:
#subtraction of matrices
z-r

array([[-4, -4],
       [-4, -4]])

In [52]:
# Multiplication of matrices
z*r

array([[ 5, 12],
       [21, 32]])

In [53]:
# Division of matrices
z/r

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [54]:
# This is for squareroot
z**r

array([[    1,    64],
       [ 2187, 65536]])

# Note
Multiplication in matrix is not done using a star but a dot and it brings an inner or outer dot product

A matrix is assigned with values on top of the order and a vector has the values only.

In [67]:
#This is for a vector 
h = np.array([9,10])
o = np.array([11,12])
#This is for vector inner dot product
h.dot(o)
o.dot(h)
np.dot(h,o)

219

In [65]:
#matrix.vector
z.dot(h)
r.dot(o)
#This is for vector outer dot product and the answer will appear like this;
array([127, 173])


array([127, 173])

In [71]:
#This is for matrix matrix
z.dot(r)
r.dot(z)
# This is an inner dot product of matrix and the answer is;
array([[23, 34],
       [31, 46]])

array([[23, 34],
       [31, 46]])

# Transpose of a matrix

In [73]:
#This is for Transpose
z = np.array([[1,2],[3,4]])
r = np.array([[5,6],[7,8]])
print(z.T)
print(r.T)
#Nb in jupyter the transpose cannot be vertical its always horizontal

[[1 3]
 [2 4]]
[[5 7]
 [6 8]]
